# API Keys
api_keys:
  openai: ""  # GPT models
  anthropic: "your-anthropic-api-key"  # Claude models
  gemini: ""  # Gemini models
  huggingface: ""  # To download models from HuggingFace

model_path:
  huggingface: "models"  # directory to store downloaded models

# Dataset
data:
  root: "/Users/nicolas/Desktop/LightEMMA/mininu"  # Path to nuScenes dataset
  version: "v1.0-mini"  # Dataset version (v1.0-mini, v1.0-trainval, v1.0-test)
  results: "/Users/nicolas/Desktop/LightEMMA/results"  # Local directory to store results

# Prediction Parameters (do not change)
prediction:
  obs_len: 6  # Number of past observations (frames)
  fut_len: 6  # Number of future predictions (frames)
  ext_len: 2  # Extra length for calculations (frames)